spring:
  application:
    name: admin-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/savingsgroup_admin
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss
    time-zone: UTC
  task:
    scheduling:
      pool:
        size: 5
      thread-name-prefix: admin-scheduler-
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-server/issuer
  profiles:
    active: dev

---
spring:
  config:
    activate:
      on-profile: dev
  data:
    mongodb:
      uri: mongodb://localhost:27017/savingsgroup_admin

---
spring:
  config:
    activate:
      on-profile: prod
  data:
    mongodb:
      uri: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_HOST}:${MONGO_PORT}/savingsgroup_admin

server:
  port: 8084

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.uuid}

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
  circuitbreaker:
    enabled: true

jwt:
  secret: ${JWT_SECRET:defaultSecretKeyWhichShouldBeOverriddenInProduction}
  expiration: 86400000  # 24 hours in milliseconds

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true
  info:
    git:
      mode: full
  metrics:
    export:
      prometheus:
        enabled: true

resilience4j:
  circuitbreaker:
    instances:
      userService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 5
        slidingWindowType: COUNT_BASED
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
      groupService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 5
        slidingWindowType: COUNT_BASED
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
      notificationService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 5
        slidingWindowType: COUNT_BASED
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
      transactionService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 5
        slidingWindowType: COUNT_BASED
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
      gamificationService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 5
        slidingWindowType: COUNT_BASED
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
  timelimiter:
    instances:
      userService:
        timeoutDuration: 2s
      groupService:
        timeoutDuration: 2s
      notificationService:
        timeoutDuration: 2s
      transactionService:
        timeoutDuration: 2s
      gamificationService:
        timeoutDuration: 2s
  retry:
    instances:
      userService:
        maxAttempts: 3
        waitDuration: 1s
        enableExponentialBackoff: true
      groupService:
        maxAttempts: 3
        waitDuration: 1s
        enableExponentialBackoff: true
      notificationService:
        maxAttempts: 3
        waitDuration: 1s
        enableExponentialBackoff: true
      transactionService:
        maxAttempts: 3
        waitDuration: 1s
        enableExponentialBackoff: true
      gamificationService:
        maxAttempts: 3
        waitDuration: 1s
        enableExponentialBackoff: true

logging:
  level:
    com.savingsgroup.adminservice: INFO
    org.springframework.data.mongodb: INFO
    org.springframework.web: INFO
    org.springframework.cloud.openfeign: DEBUG